### ISSUE TITLE
Transparent encription integration on ESP-NOW using dynamic key

### ISSUE THREAD

**Issue by gmag11** [iphong/esphome-espnow#2]
Hi, I've been working on ESP-NOW for a while. You can find my work on https://github.com/gmag11/EnigmaIOT. Maybe you find it useful for your project

**Comment by iphong** [comment]
Atually I have already looked at your project a while ago when I started this. Great works! 

However, this.project is just a practice playground for my other project which i'm working on right now (
https://github.com/iphong/esp-visual-led). It does have quite a few challenges that i am trying to solve right now:

* The protocol needs to be super lightweight, because messages are being sent every milliseconds and even higher rates
* The protocol doesn't require secured encryption, and any other unescessary computes which can affect the performance
* During light show session, master node will continuously broadcast sync and controls messages repeatedly so it's ok if a few messages get lost. As long as slave nodes receives 1 message per second, then it should be able to re-adjust its timeline in perfect sync
* Sending large files from host to multiple nodes at once (files are stored in 16Mb internal flash on each node)
